workflows:
  build_stk_cheat:
    name: Build SuperTuxKart Cheater APK
    environment:
      groups:
        - linux
      vars:
        SDK_PATH: $CM_ANDROID_SDK
        NDK_PATH: $CM_ANDROID_NDK
        BUILD_TYPE: release
        PROJECT_VERSION: git
        PROJECT_CODE: 69
        COMPILE_ARCH: armv7
    scripts:
      - name: Install system deps
        script: |
          apt-get update && apt-get install -y \
            autoconf automake make python3 python3-pip gradle imagemagick cmake \
            vorbis-tools pngquant advancecomp libjpeg-progs optipng ninja-build curl unzip
      - name: Generate assets
        script: |
          chmod +x generate_assets.sh
          ./generate_assets.sh
      - name: Build dependencies
        script: |
          chmod +x make_deps.sh
          ./make_deps.sh
      - name: Build APK
        script: |
          chmod +x make.sh
          ./make.sh -j$(nproc)
    artifacts:
      - android/bin/*.apk
